### ISSUE TITLE
Verify DGC  for any country

### ISSUE THREAD

**Issue by chauhan-rohit** [DevTrevi/DgcReader#5]
Hello @DevTrevi ,

I am from an airline IT team and we are creating an application to use DGC for retrieving Vaccination information. This information is needed to determine whether traveler is allowed to fly to particular destination based on destination country covid rules. We are able to decode the DGC QR code using your library but struggling with Verification process.  Our use case is to accept DGC for all countries. We referred the below official docs, but couldn't figure out how a third party can verify a DGC for any country
https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v4_en.pdf
https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v5_en.pdf

**Comment by DevTrevi** [comment]
Hi @chauhan-rohit, unfortunately I am not sure of the specific rules needed for your use case.

From a legal perspective, I can not give you any advice on using this library within your service.

From a technical point of view, in order to check if a green certificate is valid for a given country, you should implement and use a different rules validator for every country of interest.

As far as I know, there are no services capable of validating the rules for all the EU countries, because every country is implementing its own backend without using a standard format for the rules.
There was some guidelines for implementing a common format for rules validation, but they seems abandoned...

Here in this repository you can find an unofficial implementation for validation of the Italian rules (DgcReader.ItalianRulesValidator), but for your use case seems to be not sufficient, you will need validator providers for all the other countries as well.

So, if your goal is to validate a Digital Green Certificate with the *precise* rules for every country, I think that there are no solutions at the moment (except implementing every missing Rules validator).  
But if your use case allows a less "precise" validation, maybe you can rely on the "Valid" status of the italian rules validator result. The "Valid" result is more strict than the "Partially valid", and should be considered valid in most EU countries, at least for entering the country, but I can not guarantee that this solution will work for your scenario, as there is an high probability that the result will not be compliant with the country of arrival rules
