### ISSUE TITLE
Xamarin - Initial qrCode validation result takes more than 3 minutes

### ISSUE THREAD

**Issue by vlajkoe** [DevTrevi/DgcReader#55]
Hi @DevTrevi,

I am using Xamarin (.NET Standard 2.0) shared Library.
I instantiated the service:

```
var httpClient = new HttpClient();
var trustListProvider = ItalianTrustListProvider.Create(httpClient,
 new ItalianTrustListProviderOptions
 {
   RefreshInterval = TimeSpan.FromHours(24),
   MinRefreshInterval = TimeSpan.FromHours(1),
   BasePath = System.IO.Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory,"tl"),
   SaveCertificate = true
  });
var drlBlacklistProvider = ItalianDrlBlacklistProvider.Create(httpClient,
 new ItalianDrlBlacklistProviderOptions
 {
   RefreshInterval = TimeSpan.FromHours(24),
   MinRefreshInterval = TimeSpan.FromHours(1),
   BasePath = System.IO.Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "bl"),
   UseAvailableValuesWhileRefreshing = true,
  });
var rulesValidator = DgcItalianRulesValidator.Create(httpClient,
 new DgcItalianRulesValidatorOptions
 {
   RefreshInterval = TimeSpan.FromHours(24),
   MinRefreshInterval = TimeSpan.FromHours(1),
   BasePath = System.IO.Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "rl"),
   ValidationMode = ValidationMode.Strict2G
  });

DgcReaderService dgcReader = DgcReaderService.Create(
 trustListProviders: new[] { trustListProvider },
 blackListProviders: new IBlacklistProvider[] { rulesValidator, drlBlacklistProvider },
 rulesValidators: new[] { rulesValidator });
```

And when I try to get ValidationResult,  only for first (newly installed app or cache deleted ) call:

```
Stopwatch sw = new Stopwatch();
sw.Start();
string code = @"HC1:6BFOXN%TS3DH0YOJ58S S-W5HDC *M0II5XHC9B5G2+$N IOP-IA%NFQGRJPC%OQHIZC4.OI1RM8ZA.A5:S9MKN4NN3F85QNCY0O%0VZ001HOC9JU0D0HT0HB2PL/IB*09B9LW4T*8+DCMH0LDK2%K:XFE70*LP$V25$0Q:J:4MO1P0%0L0HD+9E/HY+4J6TH48S%4K.GJ2PT3QY:GQ3TE2I+-CPHN6D7LLK*2HG%89UV-0LZ 2ZJJ524-LH/CJTK96L6SR9MU9DHGZ%P WUQRENS431T1XCNCF+47AY0-IFO0500TGPN8F5G.41Q2E4T8ALW.INSV$ 07UV5SR+BNQHNML7 /KD3TU 4V*CAT3ZGLQMI/XI%ZJNSBBXK2:UG%UJMI:TU+MMPZ5$/PMX19UE:-PSR3/$NU44CBE6DQ3D7B0FBOFX0DV2DGMB$YPF62I$60/F$Z2I6IFX21XNI-LM%3/DF/U6Z9FEOJVRLVW6K$UG+BKK57:1+D10%4K83F+1VWD1NE";
DgcReader.Models.DgcValidationResult result = await dgcReader.GetValidationResult(code, "IT");
sw.Stop();
Logger.Instance.Info($"GetValidationResult took {sw.Elapsed} to finish.");
```
it takes more than 3 minutes to finish (tested on 3 different Android and iOS devices):
GetValidationResult took 00:05:32.9229188 to finish. 
GetValidationResult took 00:03:30.3414527 to finish. 
GetValidationResult took 00:03:14.6817884 to finish. 

After the first call of "GetValidationResult", every other call takes 1-6 seconds to get the result (which is ok), even if the app restarts.

Any idea why is this happening?

**Comment by DevTrevi** [comment]
Hi @vlajkoe , the cause of the wait time of ~3 minutes for the first validation is due to the initial download of the blacklist. 
If the blacklist is empty, the download is awaited even if the parameter `UseAvailableValuesWhileRefreshing` is true.

Maybe I can add a parameter to avoid awaiting the results for blacklist provider even if empty, or I can expose an event to notify the download progress for the blacklist, so you can show a progress indicator on the UI.

After the first download, the validation time should be below 1s (testing on Xamarin.Forms with Android emulator I get timings between 0.03s and 0.6s)
Here my test, showing reference timings for each provider on Android emulator:
![image](https://user-images.githubusercontent.com/5840474/150795424-ad58eeea-30ac-430d-a579-b12822b6ff6c.png)

The blacklist takes a long time because at the moment it contains more than 500k entries, downloaded in 51 chunks of ~500Kb each, so it takes about 3s for each chunk to be downloaded and stored in the local DB.
If you can, I also suggest you to update your xamarin.forms target to netstandard2.1, in this way you will use a more recent version of EF Core (version 5 instead of version 3.1)

Finally, if you can pass a logger instance to the library you can get more accurate informations about dowload timings and errors
Here an example:
``` csharp
var loggerFactory = LoggerFactory.Create(c =>
{
    c.SetMinimumLevel(LogLevel.Debug);
    c.AddDebug().AddConsole();
});

var basePath = FileSystem.AppDataDirectory;

var httpClient = new HttpClient();
ItalianTrustListProvider = ItalianTrustListProvider.Create(httpClient,
    options: new ItalianTrustListProviderOptions() { BasePath = basePath, },
    logger: loggerFactory.CreateLogger<ItalianTrustListProvider>());

ItalianRulesValidator = DgcItalianRulesValidator.Create(httpClient,
    new DgcItalianRulesValidatorOptions { BasePath = basePath, },
    logger: loggerFactory.CreateLogger<DgcItalianRulesValidator>());

ItalianDrlBlacklistProvider = ItalianDrlBlacklistProvider.Create(httpClient,
    new ItalianDrlBlacklistProviderOptions { BasePath = basePath },
    logger: loggerFactory.CreateLogger<ItalianDrlBlacklistProvider>());

DgcReaderService = DgcReaderService.Create(
    new[] { ItalianTrustListProvider },
    new IBlacklistProvider[] { ItalianRulesValidator, ItalianDrlBlacklistProvider },
    new[] { ItalianRulesValidator },
    loggerFactory.CreateLogger<DgcReaderService>());
```

**Comment by andrekiba** [comment]
is there the possibility to move the download of the blacklist in a separate public method so that we can schedule a background job for example?

**Comment by DevTrevi** [comment]
Yes, you can already call the `Refresh*` method of each provider in order to download updated values based on a schedule, or by user interaction...
You can then start the download immediately when the app is launched, but this will not solve the problem of the initial download, you can only optimize subsequent updates

``` csharp
await italianDrlBlacklistProvider.RefreshBlacklist();

// or
foreach(var p in dgcReader.BlackListProviders)
{
    await p.RefreshBlacklist();
}
```

**Comment by mircoianese** [comment]
> Maybe I can add a parameter to avoid awaiting the results for blacklist provider even if empty

Hello,
+1, I think the parameter would be useful, it would be nice to skip the blacklist validation if the list is empty (on the first run).

**Comment by andrekiba** [comment]
> Yes, you can already call the `Refresh*` method of each provider in order to download updated values based on a schedule, or by user interaction... You can then start the download immediately when the app is launched, but this will not solve the problem of the initial download, you can only optimize subsequent updates
> 
> ```cs
> await italianDrlBlacklistProvider.RefreshBlacklist();
> 
> // or
> foreach(var p in dgcReader.BlackListProviders)
> {
>     await p.RefreshBlacklist();
> }
> ```

yes, the idea is to try to fire the first refresh as soon as the app starts, in a background service. To do this I add the black list provider into the DI container (FreshIOC in Xamarin is not powerful as the ServiceCollection or any other well known DI container...) and then resolve it the service.

**Comment by manuel-esselink** [comment]
> Maybe I can add a parameter to avoid awaiting the results for blacklist provider even if empty

Sorry, what is the sense of this?
Without Blacklist you can't do a full GP validation..

**Comment by DevTrevi** [comment]
I asked if this featurecomplies with the offical sdk, but since DRL validation is mandatory, first download can't be delayed.
I will expose an event about the downlaod progress instead, so the application can show the progress to the user
[Here you can find the answer](https://github.com/ministero-salute/it-dgc-documentation/issues/14#issuecomment-1022265951)

**Comment by DevTrevi** [comment]
Buonasera @andreabonassi, in effetti potrebbe essere utile lanciare un errore in caso di regole non aggiornate, per evitare che l'aggiornamento venga avviato dal metodo Verify e gestirlo in modo esplicito. Cercherò di inserire un'opzione nella prossima versione per gestire questo comportamento 👍

**Comment by DevTrevi** [comment]
Hi everyone, I have added the `DownloadProgressChanged` event to the `ItalianDrlBlacklistProvider`. You can subscribe to this event and show a progress indicator to the user:

``` csharp
var blacklistProvider = ServiceProvider.GetRequiredService<ItalianDrlBlacklistProvider>();

blacklistProvider.DownloadProgressChanged += (sender, args) =>
{
    // Example:
    MyProgressIndicator.IsVisible = !args.IsCompleted;
    MyProgressIndicator.Percent = (int)args.TotalProgressPercent * 100;  // Percent from 0 to 100
    Console.WriteLine($"Progress: {args.TotalProgressPercent:p}");  // Progress: 12,50%
};
```

You can also access the instance of `ItalianDrlBlacklistProvider` in this way if you don't use DI:
``` csharp
var blacklistProvider = dgcReader.BlackListProviders
        .OfType<ItalianDrlBlacklistProvider>()
        .SingleOrDefault();
```
