### ISSUE TITLE
Testing multiple ValidationMode

### ISSUE THREAD

**Issue by Robotex** [DevTrevi/DgcReader#66]
Use case: I would like to test a DCC for both Basic3G and Strict2G in Italy, and return the highest validation mode it can pass (or NotValid if none).

Does this SDK support this use case without configuring and instantiating multiple DgcReaderService?

**Comment by rawmain** [comment]
Hello @Robotex 

> Use case: I would like to test a DCC for both Basic3G and Strict2G in Italy, and return the highest validation mode it can pass (or NotValid if none).

Such use case - multiple status output with single validation flow - is allowed by Italian regulations & GPDP provisions only for testing/debugging purposes.

**NOT allowed in production environment** = the right flow for production environment checks is indeed : 

1. Choose/set the right scanmode for your specific check scenario, in order to use its specific go-no-go ruleset

2. Perform single validation flows according to such ruleset

3. Return single output status

This is why (since February) the authorized verifier-apps/platforms will have to support 2 new scanmodes (SCUOLA - LAVORO) together with the current ones (BASE - RAFFORZATA - BOOSTER).

You can find further details about it on the official Italian DGC Documentation repo (_new scanmodes' documentation is already in the PR-tracker_).

https://github.com/ministero-salute/it-dgc-documentation/blob/master/SCANMODE.md

**Comment by Robotex** [comment]
Hello @rawmain 

> Hello @Robotex
> 
> > Use case: I would like to test a DCC for both Basic3G and Strict2G in Italy, and return the highest validation mode it can pass (or NotValid if none).
> 
> Keep anyway in mind that, even when technically feasible, such use case - status output with mixed/multiple scanmodes in single return - is allowed by Italian regulations & GPDP provisions **in third-party verifier-apps/platforms only for private testing/debugging purposes**.
> 
> **NOT allowed to verifier-apps/platforms in production/public environment** = the right flow for production environment 3rd party checks is indeed :
> 
>     1. Choose/set the right scanmode for your specific check scenario, in order to use its specific go-no-go ruleset
> 
>     2. Perform single validation flows - only according to such ruleset
> 
>     3. Return single output status & only related to the selected scanmode
> 
> 
> This is why (since February) DPCM 12/10/2021 compliant SDK/Libraries have to support 2 new scanmodes (SCUOLA - LAVORO) in addition to the current ones (BASE - RAFFORZATA - BOOSTER).
> 
> You can find further details about the scanmodes' flows in the official Italian DGC Documentation repo (_new scanmodes' documentation is already in the PR-tracker_).
> 
> https://github.com/ministero-salute/it-dgc-documentation/blob/master/SCANMODE.md
> 
> There is indeed only 1 Italian usage-scenario where such case is allowed = personal wallet-apps/software that include DGC validation checks.
> 
> Only in such situation there are no compliance issues, since the DGC holder and the verifier-operator are the same person.

First of all, I would like to thank you for your prompt answer.
To explain and add further details to the use case I described earlier, a commercial space has only one entrance, but serves both food (which requires a Strict2G DCC) and monopoly goods (needs only Basic3G). The customer/passer-by is asked for which service he wants to enter and his QR gets scanned by staff with VerificaC19 app. A "bar tabacchi" would be a realistic example of this case.
My client has requested to offload such entry checks to an automated self service system. 
If I understood your answer correctly, in a production/public scenario:
>     1. Choose/set the right scanmode for your specific check scenario, in order to use its specific go-no-go ruleset
> 
>     2. Perform single validation flows - only according to such ruleset
> 
>     3. Return single output status & only related to the selected scanmode
I desume that 2 separate QR scanners are needed (or a touchscreen) to let the customer choose which service he/she needs to access to. The same backend process then can run the validation flow associated to that scanner/user choice, without needing to duplicate the hardware (except eventually for the QR scanner).
Is it correct?

**Comment by DevTrevi** [comment]
Hi @Robotex, for your use case, I think that the user could choose from the touch screen which service wnat to access, without the need for multiple scanner, then you can map each service to the required validation mode, scan the qr code and give the ticket to the user for that specific service.
You can do it with a single instance, by using the extension method `VerifyForItaly` that accepts the validation mode for every request:
``` csharp
// Example
var res = await reader.VerifyForItaly(qrcode, ValidationMode.Booster, false);
```

I think that this use case will be compliant with current rules, as you will return a result for a single scan mode for every validation request.
@rawmain : can you please confirm that this use case is legit?

**Comment by rawmain** [comment]
Hello @Robotex & @DevTrevi 

> I desume that 2 separate QR scanners are needed (or a touchscreen) to let the customer choose which service he/she needs to access to.
[...]
> I think that the user could choose from the touch screen which service want to access, without the need for multiple scanner

Since there is a single entrypoint to multiple environments with different scanmode scenarios, the most efficient solution is indeed the single totem/touchscreen device with scanmode menu onscreen.

It's just enough to set it in order to return everytime to scanmode selection screen after displaying the validation output & releasing the paper-ticket.

> On the printed ticket we can report the requested service, the validation date, the name and if the scanned DCC for that service is valid or not.

Right.

According also to GPDP provisions, the paper-tickets must contain the same infos - decoded/read from DGC - that you see from the status output window of VerificaC19 verifier-app. It means :

- Applied Scanmode
- Validation date & time
- Validation Status (_so VALID or NOT_VALID in this case_)
- Name/Surname & Birthdate of the DGC holder

The addition on top (or bottom) of the paper-ticket of fields such as business name / address of the venue and/or requested service/access (_such as food or tobacco shop_) is also allowed.
